spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_system
#    url: jdbc:mysql://localhost:3306/health_system?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  驼峰和下划线命名规则自动映射
Mybatis:
  configuration:
    map-underscore-to-camel-case: true